all: 1_swap.c 2_minmax.c 3_arrptr.c 4_printptr.c 5_sumptr.c
	$(CC) -o exe_1 1_swap.c 
	$(CC) -o exe_2 2_minmax.c
	$(CC) -o exe_3 3_arrptr.c
	$(CC) -o exe_4 4_printptr.c
	$(CC) -o exe_5 5_sumptr.c

del:
	$(RM) exe_*
